### ISSUE TITLE
Putting .exe on GitHub

### ISSUE THREAD

**Issue by idontknowanyoneonhere** [d1xlord/Illume#1]
Could you put the full `.rar` that includes the `.exe` and other files here on GitHub?

**Comment by na-fis** [comment]
Hi, you could make the .exe file yourself by installing the libraries (tkinter and cue_sdk) and using pyinstaller. Alternatively you can download it from [here](https://drive.google.com/file/d/0B1VdBO1_gqfbSjE5d3p1ZllrS2M)
